### ISSUE TITLE
What are the odds of having python 3 compatibility?

### ISSUE THREAD

**Issue by F483** [gerold-penz/python-jsonrpc#25]
I would like to port my lib apigen ( https://pypi.python.org/pypi/apigen ) to support both Python 2 & 3 simultaneously but am currently held back by my dependence to python-jsonrpc.

What are the chances of python-jsonrpc python 3 compatibility in the near future?

**Comment by gerold-penz** [comment]
Hi F483!

I have no praxis with programming in Python 3. All my programs are written in Python 2 and the "Google App Engine" only supports Python 2. Since I don't need Python 3 support (in the next 1 or 2 years), I can not spend time to adapt python-jsonrpc to Python 3.

Regards,
Gerold

**Comment by F483** [comment]
I do not see any unit tests. If the examples have sufficient coverage I may consider porting it myself so it works with python 2.7 and python 3.
Would requiring 2.7 if using python 2 be acceptable for you?

See https://docs.python.org/3/howto/pyporting.html

**Comment by gerold-penz** [comment]
Hi F483!

Thank you for your offer. But, because I have no experience with Python 3, I would not longer be in a position to develop further the python-jsonrpc library.
Please fork "python-jsonrpc" and make your own library. As soon as I am familiar with Python 3, I will port "python-jsonrpc" to Python 3. Then, your fork will be a great help for me.

Regards,
Gerold

**Comment by F483** [comment]
Python 3 is very easy to pick up and the differences are minor, you wont notice a difference for the most part.

It took me only 1 hour to port another lib of mine with no prior python 3 experience.

This is a great cheat sheet for the differences http://python-future.org/compatible_idioms.html
